name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.craftaro.epicfarming.EpicFarming
softdepend:
  - Arconix
  - ASkyBlock
  - DecentHolograms
  - FabledSkyBlock
  - Factions
  - GriefPrevention
  - Kingdoms
  - PlaceholderAPI
  - PlayerPoints
  - PlotSquared
  - RedProtect
  - Reserve
  - SkyBlock
  - StackMob
  - Towny
  - UltimateStacker
  - USkyBlock
  - Vault
  - WildStacker
  - WorldGuard

author: Craftaro
website: ${project.url}

# TODO: cleanup commands section
commands:
  EFA:
    description: View information on this plugin.
    default: true
    aliases: [ EpicFarming ]
    usage: /efa
